# Generated by Django 4.2.5 on 2024-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="passed_out",
            field=models.BooleanField(default=False),
        ),
    ]
